config/routes.rb
Rails.application.routes.draw do

  get 'chats/show'
  #get 'posts/index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users


  get 'chat/:id', to: 'chats#show', as: 'chat'

  resources :users
  resources :chats, only: [:create]
  
  root to: "posts#index"
  resources :posts 
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  validates :text, presence: true, length: {maximum: 140}
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do

      validates :nickname
      validates :age
    end
    
    enum gender: { man: 0, woman: 1}
    has_many :posts

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?






private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:nickname, :age, :gender])
  end





end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
   #Aさん=自分、Bさん=相手
   #BさんのUser情報を取得
   @user = User.find(params[:id])
   #user_roomsテーブルのuser_idがAさんのレコードのroom_idを配列で取得
    rooms = current_user.user_rooms.pluck(:room_id)
   #user_idがBさん(@user)で、room_idがAさんの属するroom_id（配列）となるuser_roomsテーブルのレコードを取得して、user_room変数に格納
   #これによって、AさんとBさんに共通のroom_idが存在していれば、その共通のroom_idとBさんのuser_idがuser_room変数に格納される（1レコード）。存在しなければ、nilになる。
    user_room = UserRoom.find_by(user_id: @user.id, room_id: rooms)
 
   #user_roomでルームを取得できなかった（AさんとBさんのチャットがまだ存在しない）場合の処理  
    room = nil
    if user_room.nil?
    #roomのidを採番
     room = Room.new
     room.save
     #採番したroomのidを使って、user_roomのレコードを2人分（Aさん用、Ｂさん用）作る（＝AさんとBさんに共通のroom_idを作る）
     #Bさんの@user.idをuser_idとして、room.idをroom_idとして、UserRoomモデルのがラムに保存（1レコード）
      UserRoom.create(user_id: @user.id, room_id: room.id)
     #Aさんのcurrent_user.idをuser_idとして、room.idをroom_idとして、UserRoomモデルのカラムに保存（1レコード）
      UserRoom.create(user_id: current_user.id, room_id: room.id)
    else
     #user_roomに紐づくroomsテーブルのレコードをroomに格納
      room = user_room.room
    end
 
    #roomに紐づくchatsテーブルのレコードを@chatsに格納
     @chats = room.chats
    #form_withでチャットを送信する際に必要な空のインスタンス
    #ここでroom.idを@chatに代入しておかないと、form_withで記述するroom_idに値が渡らない
     @chat = Chat.new(room_id: room.id)
   end
 
   def create
     @chat = current_user.chats.new(chat_params)
     @chat.save
     redirect_to request.referer
   end
 
   private
 
   def chat_params
     params.require(:chat).permit(:message, :room_id)
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      @users = User.where.not(id: current_user.id)
    end
    @posts = Post.includes(:user).order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)

    redirect_to root_path
  end

  def show
  end

  def edit
  end

  def update
    @post.update(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  # def search
  # end

  private

  def post_params
    params.require(:post).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

    @nickname = current_user.nickname
    @posts = current_user.posts

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/create.js.erb
/*.messageを部分更新。appendメソッドで要素を追加 */
$('.message').append("<p style='text-align: left;'><%= @chat.message %></p>");

/*チャット投稿後、フォームの値に前回の投稿内容が残らないようにする */
$('input[type=text]').val("")

app/views/chats/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-6">
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %>
            <h2>CHAT WITH <%= @user.nickname %></h2>

            <table class="message table">
              <thead>
                <tr>
                  <th style="text-align: left; font-size: 20px;"><%= current_user.nickname %></th>
                  <th style="text-align: right; font-size: 20px;"><%= @user.nickname %></th>
                </tr>
              </thead>
              <% @chats.each do |chat| %>
                <% if chat.user_id == current_user.id %>
                <tbody>
                  <tr>
                    <th>
                      <p style="text-align: left;"><%= chat.message %></p>
                    </th>
                    <th></th>
                  </tr>
                <% else %>
                  <tr>
                    <th></th>
                    <th>
                      <p style="text-align: right;"><%= chat.message %></p>
                    </th>
                  </tr>
                </tbody>
                <% end %>
              <% end %>
            </table>

            <%= form_with model: @chat, remote: true do |f| %>
              <%= f.text_field :message %>
              <%= f.hidden_field :room_id %>
              <%= f.submit "SEND", class:"btn btn-sm btn-success chat-btn" %>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/chat_room/show.html.erb
<link type="text/css" rel="stylesheet" href="chat_room.css" />


<h2 style= "text-align:center"><%="#{hoge}さんとのチャット"%></h2>
<div id="chats">
  <% @chats.each do |chat| %>
   <%if chat.user_id==current_user.id%>
    <div class="comment_user">
        <p><%=chat.sentence%></p>
    </div>
   <%else%>
    <div class="fukidashi">
      <div class="icon">
        <img scr="/" alt="ゲスト">
      </div>
      <div class="chatting">
        <div class="says">
          <p>
            <%=chat.sentence%>
          </p>
        </div>
      </div>
    </div>
   <% end %>
  <% end %>
  </div>

  
<form id="send-form">
  <input type="text" id="hoge" placeholder="入力" style="width:30%;">
  <input id="send_btn" type="submit" value="送信" id="send">
  <input id="current_user_id" type="hidden" value= "<%=current_user.id%>">
  <input id="hoge_id" type="hidden" value= "<%=@partner.id%>">
</form>  

app/views/posts/index.html.erb
<% if user_signed_in? %> 
  <%= current_user.nickname %>さん
  <ul>
    <li><%= link_to "マイページ", "/users/#{current_user.id}", class: "nickname" %></li>
    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"logout" %></li>
    <li><%= link_to "新規投稿", new_post_path %></li>
    <li><%= link_to "チャットルーム作成", chats_path, method: :post %></li>
  </ul>
<% else %>
  <ul>
    <li><%= link_to 'ログイン', new_user_session_path, class:"sign-in"%></li>
    <li><%= link_to '新規登録', new_user_registration_path, class:"sign-up"%></li> 
  </ul>
<% end %>

<div class="d-flex align-items-center">
    <h1>投稿一覧</h1>
</div>
<table>
  <thead>
    <tr>
      <th scope="col">募集内容</th>
      <th scope="col">投稿者</th>
      <th scope="col">投稿日</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
      <% @posts.each do |post| %>
        <tr>
            <td><%= post.text %></td>
            <td><%= post.user.nickname %></td>
            <td><%= post.created_at.to_s(:datetime_base) %></td>
            <td><%= link_to "詳細" , post_path(post.id), method: :get %></td>
            <td><%= button_to "削除" , post_path(post.id), method: :delete %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/posts/index/html.erb
<h1>トップページ<h1>

app/views/posts/new.html.erb
<%# 投稿ページです %>
<div class="container">
  <div class="head">
    <h3>募集する</h3>
  </div>
  <%= form_with(model: @post, local: true) do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
    <div class="post-field">
      <%= f.text_area :text, placeholder:"本文" %>
      <%# <div class="click-upload"> %>
        <%# <p>クリックしてファイルをアップロード</p> %>
        <%# <%= f.file_field :image, id:"item-image"%>
      <%# </div> %>
      <%# <%= f.text_field :name, placeholder:"タグ" %>
    </div>

    <div class="submit-post">
      <%= f.submit "投稿する"%>
    </div>
    
  <% end %>
</div>

app/views/posts/show.html.erb
ddd

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="contents s">
<p>ID<%= @user.id%></p>
<p>ニックネーム<%= @user.nickname %>さん</p>
<p>性別<%= @user.gender %></p>
<p>年齢<%= @user.age%></p>
</div>
<div class="contents u">
  <p><%= @nickname %>さんの投稿一覧</p>
  </div>
<table class="table table-bordered border-primary table-hover table-sm posts_table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">募集内容</th>
      <th scope="col">投稿者</th>
      <th scope="col">投稿日</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
      <% @posts.each do |post| %>
        <tr>
            <td><%= post.text %></td>
            <td><%= post.user.nickname %></td>
            <td><%= post.created_at.to_s(:datetime_base) %></td>

            <td><%= link_to "詳細" , post_path(post.id), method: :get %></td>

            <td><%= button_to "削除" , post_path(post.id), method: :delete %></td>
        </tr>
      <% end %>
  </tbody>
</table>
  <div><%= link_to"トップページへ", root_path%></div>
  <%if current_user.id? && @user.id %>
    <%= link_to "プロフィール編集", root_path%>
  <%end%>

<% if current_user != @user %>
  <%= link_to 'Begin Chat', chat_path(@user.id) %>
<% end %> 